service: marigold-custom-scraping

provider:
  name: aws
  environment:
    ENV: ${self:provider.stage}
  region: eu-central-1
  runtime: python3.12  # ← Change this
  stage: ${opt:stage, "dev"}

functions:
  scraper:
    handler: scrapers.scraper.handler  # ← Add this
    memorySize: 256
    timeout: 300  # 5 minutes
    # Remove the image section for now
    events:
      - schedule: rate(1 day)