service: marigold-custom-scraping

provider:
  name: aws
  environment:
    ENV: ${self:provider.stage}
  region: eu-central-1
  stage: ${opt:stage, "dev"}

functions:
  scraper:
    image:
      uri: 415187010298.dkr.ecr.eu-central-1.amazonaws.com/marigold-scraping-python:latest
    memorySize: 256
    timeout: 300
    events:
      - schedule: rate(1 day)