# serverless.yml

service: marigold-scraping-python

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: eu-central-1
  runtime: python3.13
  stage: ${opt:stage, "dev"}

functions:
  scraper:
    memorySize: 256
    timeout: 60
    image:
      uri: 415187010298.dkr.ecr.eu-central-1.amazonaws.com/marigold-scraping-python
      command:
        - scrapers/scraper.handler
    events:
      - schedule: rate(1 day)