# serverless.yml

service: marigold-custom-scraping

provider:
  name: aws
  environment:
    ENV: ${self:provider.stage}
  region: eu-central-1
  runtime: python3.13
  stage: ${opt:stage, "dev"}

functions:
  scraper:
    memorySize: 256
    timeout: 60
    image:
      uri: 415187010200.dkr.ecr.eu-central-1.amazonaws.com/marigold-scraping-python:latest
    events:
      - schedule: rate(1 day)